POST http://localhost:8080/api/users
Content-Type: application/json

{
  "name": "Hannah",
  "email": "Hannah@mail.ru",
  "dob": "2005-12-01"
}

###
DELETE http://localhost:8080/api/users/1

###
PUT http://localhost:8080/api/users/2?
    email=Hannnna@mail.ru&
    name=Alexey&
    Content-Type: application/x-www-form-urlencoded
